### ISSUE TITLE
HA 2025.8.0 breaks snap support

### ISSUE THREAD

**Issue by jaroschek** [jaroschek/home-assistant-eaton-epdu#37]
> I noticed the same error (i think). This is more log output.
> 
> Error setting up entry ePDU for eaton_epdu
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/eaton_epdu/__init__.py", line 17, in async_setup_entry
>     coordinator = SnmpCoordinator(hass=hass, entry=entry, snmpEngine=snmpEngine)
>   File "/config/custom_components/eaton_epdu/coordinator.py", line 52, in __init__
>     self._api = SnmpApi(entry, snmpEngine)
>                 ~~~~~~~^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/eaton_epdu/api.py", line 61, in __init__
>     self._target = hlapi.UdpTransportTarget(
>                    ~~~~~~~~~~~~~~~~~~~~~~~~^
>         (
>         ^
>     ...<3 lines>...
>         10,
>         ^^^
>     )
>     ^
>   File "/usr/local/lib/python3.13/site-packages/pysnmp/hlapi/transport.py", line 39, in __init__
>     raise Exception(
>         f"Please call .create() to construct {self.__class__.__name__} object"
>     )
> Exception: Please call .create() to construct UdpTransportTarget object 

 _Originally posted by @Responseless in [#32](https://github.com/jaroschek/home-assistant-eaton-epdu/issues/32#issuecomment-3166925877)_

**Comment by jaroschek** [comment]
Hello @Responseless, 

I have now worked on the compatibility to `pysnmp` version `7.1.21` and created a **pre-release** version `1.4.0-rc1` of this integration.

Please give it a try!

**Comment by BigProgrammer2000** [comment]
Hello,
I have installed the new pre-release.
I am getting this issue now:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eaton_epdu/__init__.py", line 20, in async_setup_entry
    coordinator = SnmpCoordinator(hass=hass, api=api)
  File "/config/custom_components/eaton_epdu/coordinator.py", line 52, in __init__
    update_interval=timedelta(seconds=entry.data.get(ATTR_UPDATE_INTERVAL, UPDATE_INTERVAL_DEFAULT)),
                                      ^^^^^
NameError: name 'entry' is not defined`

**Comment by jaroschek** [comment]
@BigProgrammer2000, thank you very much for the test!

I missed that the latest changes for the optional dynamic update interval needed the config entry to be passed to the coordinator. I previously worked on the support for the new pysnmp version without these changes.

This is now fixed in the new pre-release 1.4.0-rc2.

**Comment by suicidaleggroll** [comment]
Unfortunately I'm still having issues with this.  Everything worked great until I upgraded HomeAssistant to 2025.8.  I was getting the same error as the first post here with this integration after upgrade.  I've now upgraded the integration to 1.4.0, but now I'm just getting timeouts.

`Failed setup, will retry: Got SNMP error: No SNMP response received before timeout 0 0`

I'm using SNMP v3 with SHA/AES.  The ePDU still works normally with snmpset from the command line with the same user/pass, this integration is just timing out without connecting now.  The only relevant output I see in the HomeAssistant log is:

```
2025-08-13 10:30:22.393 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('eaton_epdu', '01JSHY6G5NX5TSQ63B1Z3525DK'): 326782.166070418}
2025-08-13 10:37:32.341 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'eaton_epdu' sets option flow config_entry explicitly, which is deprecated at custom_components/eaton_epdu/config_flow.py, line 189: self.config_entry = entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/jaroschek/home-assistant-eaton-epdu/issues
```

Is there anywhere else I can go to find more relevant logs to see where it's failing?
